<a href="https://colab.research.google.com/github/thomhert/belajar-PyTorch/blob/master/01_dasar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
%matplotlib inline
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torchvision

In [0]:
from pprint import pprint

import matplotlib.pyplot as plt
import numpy as np
from IPython.core.debugger import set_trace

# **Membuat Tensor**

In [0]:
import numpy as np
from numpy.linalg import inv
from numpy.linalg import multi_dot as mdot

In [4]:
#numpy -> membuat matriks diagonal
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
# pytorch
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [0]:
# Membuat matriks secara acak (random)

In [0]:
X_n = np.random.random((5,4))

In [9]:
X_n

array([[0.83993221, 0.92822011, 0.68339311, 0.57806312],
       [0.10224011, 0.30221282, 0.32110765, 0.51741471],
       [0.96250253, 0.57173042, 0.70097562, 0.81244783],
       [0.42266812, 0.16613138, 0.85941345, 0.13749165],
       [0.92016628, 0.92366926, 0.19800362, 0.11924516]])

In [0]:
X_t = torch.rand((5,4))

In [11]:
X_t

tensor([[0.8936, 0.4026, 0.6184, 0.5176],
        [0.8176, 0.1887, 0.9394, 0.2330],
        [0.6870, 0.8124, 0.7143, 0.9505],
        [0.3427, 0.5849, 0.9688, 0.8280],
        [0.6269, 0.3038, 0.9628, 0.3303]])

In [12]:
X_n.shape

(5, 4)

In [13]:
X_t.shape

torch.Size([5, 4])

In [14]:
#
X_n.T @ X_n

array([[2.66770461, 2.28097996, 1.8269677 , 1.48825618],
       [2.28097996, 2.16056536, 1.45781656, 1.29042507],
       [1.8269677 , 1.45781656, 1.83930001, 1.27246944],
       [1.48825618, 1.29042507, 1.27246944, 1.29506979]])

In [15]:
X_t.t() @ X_t

tensor([[2.4493, 1.4631, 2.7470, 1.7968],
        [1.4631, 1.2921, 1.8657, 1.6091],
        [2.7470, 1.8657, 3.6408, 2.3380],
        [1.7968, 1.6091, 2.3380, 2.0202]])

In [16]:
inv(X_n.T @ X_n)

array([[ 6.15490319, -5.14826232, -2.15076508,  0.1699962 ],
       [-5.14826232,  5.53545543,  1.40270086, -0.97759308],
       [-2.15076508,  1.40270086,  2.57702164, -1.45812391],
       [ 0.1699962 , -0.97759308, -1.45812391,  2.98356959]])

In [17]:
torch.inverse(X_t.t() @ X_t)

tensor([[  3.4373,  -9.7645,  -2.4186,   7.5194],
        [ -9.7645, 124.1083,   6.5197, -97.7150],
        [ -2.4186,   6.5198,   2.7726,  -6.2508],
        [  7.5194, -97.7150,  -6.2508,  78.8728]])

# **Lanjutan**

In [0]:
A = torch.eye(3)

In [19]:
A

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [20]:
A.add(1)

tensor([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.]])

In [21]:
A

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [0]:
# nilai A tidak berubah

In [23]:
A.add_(1)

tensor([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.]])

In [24]:
A

tensor([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.]])

In [0]:
#nilai A berubah

In [26]:
A.mul(3)

tensor([[6., 3., 3.],
        [3., 6., 3.],
        [3., 3., 6.]])

In [27]:
A

tensor([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.]])

In [28]:
A.mul_(3)

tensor([[6., 3., 3.],
        [3., 6., 3.],
        [3., 3., 6.]])

In [29]:
A

tensor([[6., 3., 3.],
        [3., 6., 3.],
        [3., 3., 6.]])

# Indexing

In [30]:
A[0,0]

tensor(6.)

In [31]:
A[2]

tensor([3., 3., 6.])

In [32]:
A[:, 0:2]

tensor([[6., 3.],
        [3., 6.],
        [3., 3.]])

In [33]:
A[1,:]

tensor([3., 6., 3.])

# Converting

In [34]:
A = torch.eye(3)
A

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [35]:
# mengubah torch ke numpy
B = A.numpy()
B

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [0]:
# Catatan: torch dan numpy dapat berbagi memory (zeroc-opy)

In [37]:
A.add_(.5)

tensor([[1.5000, 0.5000, 0.5000],
        [0.5000, 1.5000, 0.5000],
        [0.5000, 0.5000, 1.5000]])

In [38]:
A

tensor([[1.5000, 0.5000, 0.5000],
        [0.5000, 1.5000, 0.5000],
        [0.5000, 0.5000, 1.5000]])

In [39]:
B

array([[1.5, 0.5, 0.5],
       [0.5, 1.5, 0.5],
       [0.5, 0.5, 1.5]], dtype=float32)

In [0]:
# Nilai A dan B sama

In [41]:
# mengubah numpy ke torch
torch.from_numpy(np.eye(3))

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]], dtype=torch.float64)

# Lanjutan

In [44]:
# mengetahui fungsi (?) yang ada di torch
[o for o in dir(torch) if not o.startswith("_")]

['AVG',
 'AggregationType',
 'Argument',
 'ArgumentSpec',
 'Block',
 'BoolStorage',
 'BoolTensor',
 'BoolType',
 'ByteStorage',
 'ByteTensor',
 'CharStorage',
 'CharTensor',
 'Code',
 'CompilationUnit',
 'CompleteArgumentSpec',
 'CudaBoolStorageBase',
 'CudaByteStorageBase',
 'CudaCharStorageBase',
 'CudaDoubleStorageBase',
 'CudaFloatStorageBase',
 'CudaHalfStorageBase',
 'CudaIntStorageBase',
 'CudaLongStorageBase',
 'CudaShortStorageBase',
 'DictType',
 'DoubleStorage',
 'DoubleTensor',
 'ExecutionPlanState',
 'ExtraFilesMap',
 'FatalError',
 'FileCheck',
 'FloatStorage',
 'FloatTensor',
 'FloatType',
 'Function',
 'FunctionSchema',
 'Future',
 'Generator',
 'Gradient',
 'Graph',
 'GraphExecutorState',
 'HalfStorage',
 'HalfStorageBase',
 'HalfTensor',
 'IODescriptor',
 'IntStorage',
 'IntTensor',
 'IntType',
 'JITException',
 'ListType',
 'LockingLogger',
 'LoggerBase',
 'LongStorage',
 'LongTensor',
 'Node',
 'NoopLogger',
 'NumberType',
 'OptionalType',
 'PyTorchFileReader',
 'Py

In [43]:
[o for o in dir(torch) if o.startswith("_")]

['_C',
 '_StorageBase',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_adaptive_avg_pool2d',
 '_baddbmm_mkl_',
 '_batch_norm_impl_index',
 '_cast_Byte',
 '_cast_Char',
 '_cast_Double',
 '_cast_Float',
 '_cast_Half',
 '_cast_Int',
 '_cast_Long',
 '_cast_Short',
 '_convolution',
 '_convolution_nogroup',
 '_copy_same_type_',
 '_ctc_loss',
 '_cudnn_ctc_loss',
 '_cudnn_init_dropout_state',
 '_cudnn_rnn',
 '_cudnn_rnn_flatten_weight',
 '_cufft_clear_plan_cache',
 '_cufft_get_plan_cache_max_size',
 '_cufft_get_plan_cache_size',
 '_cufft_set_plan_cache_max_size',
 '_debug_has_internal_overlap',
 '_dim_arange',
 '_dirichlet_grad',
 '_embedding_bag',
 '_empty_affine_quantized',
 '_fft_with_size',
 '_fused_dropout',
 '_import_dotted_name',
 '_jit_internal',
 '_log_softmax',
 '_log_softmax_backward_data',
 '_lu_with_info',
 '_masked_scale',
 '_mkldnn',
 '_multinomial_alias_

# Menggunakan GPU

In [0]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

In [46]:
device

device(type='cuda', index=0)

In [0]:
# artinya ada GPU dan sudah diaktifkan di google colab ini

In [48]:
data = torch.eye(3)
# proses data ke GPU
data.to(device)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]], device='cuda:0')

In [0]:
res = data + data

In [50]:
res

tensor([[2., 0., 0.],
        [0., 2., 0.],
        [0., 0., 2.]])

In [51]:
res.device

device(type='cpu')

In [53]:
res.to(device)

tensor([[2., 0., 0.],
        [0., 2., 0.],
        [0., 0., 2.]], device='cuda:0')

# Autograd = Differention --> Turunan

In [0]:
from torch import autograd

In [0]:
x = torch.tensor(2)

In [63]:
x.type

<function Tensor.type>

In [0]:
x = torch.tensor(2., requires_grad=True)

In [65]:
x

tensor(2., requires_grad=True)

In [66]:
print(x.requires_grad)

True


In [67]:
print(x.grad)

None


In [70]:
y = x ** 2
print("Grad of x:", x.grad)

Grad of x: None


In [71]:
y = x ** 2
y.backward()
print("Grad of x:", x.grad)

Grad of x: tensor(4.)


In [72]:
x = torch.tensor(2.)
x.backward()

RuntimeError: ignored

In [73]:
# Don't record the gradient
# Useful for inference

params = torch.tensor(2., requires_grad=True)
with torch.no_grad():
  y = x * x
  print(x.grad_fn)

None


In [0]:
lin = nn.Linear(2, 1, bias=True)

In [75]:
lin.weight


Parameter containing:
tensor([[0.6660, 0.4315]], requires_grad=True)

In [76]:
type(lin.weight)

torch.nn.parameter.Parameter

In [77]:
isinstance(lin.weight, torch.FloatTensor)


True