<a href="https://colab.research.google.com/github/thomhert/belajar-PyTorch/blob/master/01_dasar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
import torchvision
import torch.nn as nn
import numpy as np
import torchvision.transforms as transforms

Membuat Matriks

In [0]:
arr1 = [1, 2, 3, 4]

In [5]:
np.array(arr1)

array([1, 2, 3, 4])

In [6]:
torch.Tensor(arr1)

tensor([1., 2., 3., 4.])

In [0]:
arr2 = [[1,2], [3,4], [5,6]]

In [8]:
torch.Tensor(arr2)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])